apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: my-emptydir
      mountPath: /data/empty
    - name: my-hostpath
      mountPath: /data/host
  volumes:
  - name: my-emptydir
    emptyDir: {}
  - name: my-hostpath
    hostPath:
      path: /tmp/hostpath-test
      type: DirectoryOrCreate