apiVersion: apps/v1
kind: Deployment
metadata:
  name: app32
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app32
  template:
    metadata:
      labels:
        app: app32
    spec:
      containers:
        - name: frontend
          image: kareem32/app-test:1.0.0
          ports:
            - containerPort: 80