apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-rs
  template:
    metadata:
      name: forntend
      labels:
        app: nginx
    spec:
      containers:
        - name: frontend
          image: kareem32/app-test:1.0.0
          ports:
            - containerPort: 80

